name = "gm-messenger"
main = "src/index.js"
compatibility_date = "2024-09-23"

# Define a pasta public como diretório de assets/arquivos estáticos
assets = { directory = "./public" }

# Vinculação com o Cloudflare KV (Substitua o ID pelo ID do seu namespace no painel da Cloudflare)
[[kv_namespaces]]
binding = "GM_MESENGER"
id = "feaddf21f7f8420589b7ca9596772f42"
